In [1]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context 
from dash import Dash, dcc, html
import plotly.express as px
import pandas as pd
import dask.dataframe as dd

In [2]:
df = pd.read_csv('https://gist.githubusercontent.com/chriddyp/5d1ea79569ed194d432e56108a04d188/raw/a9f9e8076b837d541398e999dcbac2b2826a81f8/gdp-life-exp-2007.csv')
df

,Unnamed: 0,country,continent,population,life expectancy,gdp per capita
0,11,Afghanistan,Asia,31889923.0,43.828,974.580338
1,23,Albania,Europe,3600523.0,76.423,5937.029526
2,35,Algeria,Africa,33333216.0,72.301,6223.367465
3,47,Angola,Africa,12420476.0,42.731,4797.231267
4,59,Argentina,Americas,40301927.0,75.320,12779.379640
...,...,...,...,...,...,...
137,1655,Vietnam,Asia,85262356.0,74.249,2441.576404
138,1667,West Bank and Gaza,Asia,4018332.0,73.422,3025.349798
139,1679,"Yemen, Rep.",Asia,22211743.0,62.698,2280.769906
140,1691,Zambia,Africa,11746035.0,42.384,1271.211593
141,1703,Zimbabwe,Africa,12311143.0,43.487,469.709298

In [3]:
ddf = dd.from_pandas(df, npartitions=10)
ddf

Dask DataFrame Structure:
               Unnamed: 0 country continent population life expectancy gdp per capita
npartitions=10
0                   int64  string    string    float64         float64        float64
15                    ...     ...       ...        ...             ...            ...
...                   ...     ...       ...        ...             ...            ...
128                   ...     ...       ...        ...             ...            ...
141                   ...     ...       ...        ...             ...            ...
Dask Name: frompandas, 1 expression
Expr=df

In [ ]:
import dash_bootstrap_components as dbc

app = Dash()


def filter_df(pop_thresh):
    filt_df = ddf[ddf["population"] > pop_thresh].compute()  # Note the use of .compute() function
    return filt_df


def build_graphs():
  #  pop_thresh = 5 * 10 ** 6
  #  filt_df = filter_df(pop_thresh)

    fig_out = px.scatter(ddf.compute(), x="gdp per capita", y="life expectancy",
                         size="population", color="continent", hover_name="country",
                         log_x=True, size_max=60, template="plotly_dark")
    return fig_out


fig = build_graphs()


app.layout = dbc.Container(
    html.Div([
        dcc.Graph(
            id='life-exp-vs-gdp',
            figure=fig
        )
    ]),

)


if __name__ == '__main__':
    app.run(port=8050, debug=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit